/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import almacenproductos.CONECTAR;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author user
 */
public class RegistrarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarUsuarios
     */public int xMouse;
       public int yMouse;
    public RegistrarUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabeREGISTRARSE = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextUsuario = new javax.swing.JTextField();
        jTextTelef = new javax.swing.JTextField();
        jTextPais = new javax.swing.JTextField();
        jTextEmpresa = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPassword = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(49, 58, 115));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar2.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 20, 20));

        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jPanel4.setBackground(new java.awt.Color(121, 86, 181));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chil-hand-on-the-hand-of-an-adult.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 70, 80));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("         Ayuda");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel23MousePressed(evt);
            }
        });
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, 90));

        jPanel5.setBackground(new java.awt.Color(121, 86, 181));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ok-appproval-acceptance (1).png"))); // NOI18N
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 70, 70));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("    Registrarse");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        jLabeREGISTRARSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeREGISTRARSEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeREGISTRARSEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeREGISTRARSEMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeREGISTRARSEMousePressed(evt);
            }
        });
        jPanel5.add(jLabeREGISTRARSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 90));

        jPanel6.setBackground(new java.awt.Color(121, 86, 181));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/left-arrow-key.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 90));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("          Atrás");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 33, 100, 20));

        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 90));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 170, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 190, 440));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Datos personales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Datos de la empresa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Datos de hubicacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel4.setText("Nombre");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, 30));

        jLabel5.setText("Apellido");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 60, 30));

        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, 30));

        jLabel7.setText("usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, 30));

        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 80, 30));

        jLabel9.setText("Empresa");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 90, 30));

        jLabel10.setText("Pais");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 40, 30));

        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 50, 30));

        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel12MouseDragged(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 30));

        jTextNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 30));

        jTextApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, 30));

        jTextUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, 30));

        jTextTelef.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextTelef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelefKeyTyped(evt);
            }
        });
        jPanel1.add(jTextTelef, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 30));

        jTextPais.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPaisActionPerformed(evt);
            }
        });
        jPanel1.add(jTextPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 122, 30));

        jTextEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 180, 30));

        jTextEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 180, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 450, 10));

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 10, 410));

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 500, 20));

        jPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, 30));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPaisActionPerformed

    private void jTextEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmpresaActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
         
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jLabel12MouseDragged

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
      
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged
        int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
         
        this.setLocation(x-xMouse-510, y-yMouse);
    }//GEN-LAST:event_jLabel13MouseDragged

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
         xMouse = evt.getX();
       yMouse = evt.getY();
        System.out.println(xMouse +","+yMouse);
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
         xMouse = evt.getX();
       yMouse = evt.getY();
        System.out.println(xMouse +","+yMouse);
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        //this.jLabel14.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
       IngresarPrograma IP = new IngresarPrograma();
       IP.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        IngresarPrograma IP = new IngresarPrograma();
       IP.setVisible(true);
       this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("/imagenes/Rosado2.png"));
        jLabel21.setIcon(A);
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        ImageIcon c = new ImageIcon(getClass().getResource("/imagenes/Rosado1.png"));
        jLabel21.setIcon(c);
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("/imagenes/Rosado3.png"));
        jLabel21.setIcon(b);
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
         IngresarPrograma IP = new IngresarPrograma();
       IP.setVisible(true);
       this.dispose();
        ImageIcon c = new ImageIcon(getClass().getResource("/imagenes/Rosado1.png"));
        jLabel21.setIcon(c);
        
         ImageIcon A = new ImageIcon(getClass().getResource("/imagenes/Rosado2.png"));
        jLabel21.setIcon(A);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabeREGISTRARSEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeREGISTRARSEMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("/imagenes/Rosado2.png"));
        jLabeREGISTRARSE.setIcon(A);
    }//GEN-LAST:event_jLabeREGISTRARSEMouseEntered

    private void jLabeREGISTRARSEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeREGISTRARSEMouseExited
        ImageIcon c = new ImageIcon(getClass().getResource("/imagenes/Rosado1.png"));
        jLabeREGISTRARSE.setIcon(c);
    }//GEN-LAST:event_jLabeREGISTRARSEMouseExited

    private void jLabeREGISTRARSEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeREGISTRARSEMousePressed
         ImageIcon c = new ImageIcon(getClass().getResource("/imagenes/Rosado3.png"));
        jLabeREGISTRARSE.setIcon(c);
    }//GEN-LAST:event_jLabeREGISTRARSEMousePressed

    private void jLabeREGISTRARSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeREGISTRARSEMouseClicked
        ImageIcon c = new ImageIcon(getClass().getResource("/imagenes/Rosado1.png"));
        jLabeREGISTRARSE.setIcon(c);
        
         ImageIcon A = new ImageIcon(getClass().getResource("/imagenes/Rosado2.png"));
        jLabeREGISTRARSE.setIcon(A);
        
        if (jTextNombre.getText().equals("") || jTextApellido.getText().equals("") || jTextTelef.getText().equals("") || jTextUsuario.getText().equals("") || jPassword.equals("")  || jTextPais.getText().equals("") || jTextEmpresa.getText().equals("") || jTextEmail.getText().equals("")) { 
               
           
            
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            jTextNombre.requestFocus();
        }else{
        
        CONECTAR conectar = new CONECTAR();
       Connection conecc = conectar.conexion();
       String nombre, apellido ,usuario,contra,Email,empresa,pais;
       String telefono,tipo = "Usuario";
       
       String sql = "";
       nombre = jTextNombre.getText();
       apellido = jTextApellido.getText();
       telefono = jTextTelef.getText();
       usuario = jTextUsuario.getText();
       contra = jPassword.getText();
       Email = jTextEmail.getText();
       empresa = jTextEmpresa.getText();
       pais = jTextPais.getText();
         
        //int cod = 1;
        //++cod;
       sql = "INSERT INTO registrousuarios (Tipo, Nombre, Apellido, Telefono, Usuario, Pass, Pais, Empresa, Email) VALUES (?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement PST = conecc.prepareStatement(sql);
            //PST.setInt(1, cod);
            PST.setString(1, tipo);
            PST.setString(2, nombre);
            PST.setString(3, apellido);
            PST.setString(4, telefono);
            PST.setString(5, usuario);
            PST.setString(6, contra);
            PST.setString(7, pais);
            PST.setString(8, empresa);
            PST.setString(9, Email);
            int n = PST.executeUpdate();
            if(n>0)
            {
                JOptionPane.showMessageDialog(null, "Registro guardado");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jLabeREGISTRARSEMouseClicked

    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
         ImageIcon A = new ImageIcon(getClass().getResource("/imagenes/Rosado2.png"));
        jLabel23.setIcon(A);
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
         ImageIcon c = new ImageIcon(getClass().getResource("/imagenes/Rosado1.png"));
        jLabel23.setIcon(c);
    }//GEN-LAST:event_jLabel23MouseExited

    private void jLabel23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MousePressed
         ImageIcon c = new ImageIcon(getClass().getResource("/imagenes/Rosado3.png"));
        jLabel23.setIcon(c);
    }//GEN-LAST:event_jLabel23MousePressed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        ImageIcon c = new ImageIcon(getClass().getResource("/imagenes/Rosado1.png"));
        jLabel23.setIcon(c);
        
         ImageIcon A = new ImageIcon(getClass().getResource("/imagenes/Rosado2.png"));
        jLabel23.setIcon(A);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jTextTelefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefKeyTyped
         char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' '));
        else{JOptionPane.showMessageDialog(null, "Ingrese solo numeros");}
    }//GEN-LAST:event_jTextTelefKeyTyped

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeREGISTRARSE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEmpresa;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPais;
    private javax.swing.JTextField jTextTelef;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
